<?php

namespace Webkul\Bills\Database\Seeders;

use Illuminate\Database\Seeder;
use Webkul\Bills\Models\Bill;
use Illuminate\Support\Str;

class BillSeeder extends Seeder
{
    public function run()
    {
        $bills = [
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'HB5678',
                'bill_year' => 2024,
                'session' => 'GEN',
                'bill_number' => 'HB5678',
                'short_title' => 'Environmental Protection Act',
                'general_provisions' => 'This bill aims to enhance environmental protection measures.',
                'highlighted_provisions' => 'Increases penalties for environmental violations.',
                'subjects' => 'Environment, Conservation',
                'code_sections' => '23-45, 67-89',
                'appropriations' => '$10 million for enforcement',
                'last_action' => 'Passed House Committee',
                'last_action_owner' => 'House Environmental Committee',
                'last_action_date' => now()->subDays(5),
                'bill_link' => 'https://example.com/bills/HB5678',
                'sponsor' => 'John Doe',
                'floor_sponsor' => 'Jane Smith',
                'ai_analysis' => 'This bill has significant positive environmental impact.',
                'ai_impact_rating' => 8,
                'ai_impact_rating_explanation' => 'High impact due to stricter regulations and increased funding.',
                'level' => 2,
                'position' => 1,
                'date_entered' => now()->subDays(30),
                'is_tracked' => true,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'SB9012',
                'bill_year' => 2024,
                'session' => 'SUMMER',
                'bill_number' => 'SB9012',
                'short_title' => 'Transportation Infrastructure Bill',
                'general_provisions' => 'This bill focuses on improving state-wide transportation infrastructure.',
                'highlighted_provisions' => 'Allocates funds for road repairs and public transit expansion.',
                'subjects' => 'Transportation, Infrastructure',
                'code_sections' => '34-56, 78-90',
                'appropriations' => '$500 million for infrastructure projects',
                'last_action' => 'Introduced in Senate',
                'last_action_owner' => 'Senate Transportation Committee',
                'last_action_date' => now()->subDays(2),
                'bill_link' => 'https://example.com/bills/SB9012',
                'sponsor' => 'Alice Johnson',
                'floor_sponsor' => 'Bob Williams',
                'ai_analysis' => 'This bill could significantly improve transportation efficiency.',
                'ai_impact_rating' => 1,
                'ai_impact_rating_explanation' => 'High impact due to large-scale infrastructure improvements.',
                'level' => 1,
                'position' => 2,
                'date_entered' => now()->subDays(15),
                'is_tracked' => false,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'HB1234',
                'bill_year' => 2024,
                'session' => 'GEN',
                'bill_number' => 'HB1234',
                'short_title' => 'Education Funding Reform',
                'general_provisions' => 'This bill aims to restructure education funding allocation.',
                'highlighted_provisions' => 'Increases per-student funding and introduces new grant programs.',
                'subjects' => 'Education, Finance',
                'code_sections' => '12-34, 56-78',
                'appropriations' => '$2 billion for education',
                'last_action' => 'Passed Senate',
                'last_action_owner' => 'Senate Education Committee',
                'last_action_date' => now()->subDays(10),
                'bill_link' => 'https://example.com/bills/HB1234',
                'sponsor' => 'Emily Brown',
                'floor_sponsor' => 'Michael Green',
                'ai_analysis' => 'This bill could significantly improve educational outcomes.',
                'ai_impact_rating' => 2,
                'ai_impact_rating_explanation' => 'High impact due to substantial funding increase and targeted programs.',
                'level' => 3,
                'position' => 1,
                'date_entered' => now()->subDays(45),
                'is_tracked' => true,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'SB5678',
                'bill_year' => 2024,
                'session' => 'SPEC',
                'bill_number' => 'SB5678',
                'short_title' => 'Healthcare Accessibility Act',
                'general_provisions' => 'This bill focuses on improving healthcare access in rural areas.',
                'highlighted_provisions' => 'Provides incentives for healthcare professionals in underserved areas.',
                'subjects' => 'Healthcare, Rural Development',
                'code_sections' => '45-67, 89-01',
                'appropriations' => '$300 million for rural healthcare initiatives',
                'last_action' => 'In House Committee',
                'last_action_owner' => 'House Health Committee',
                'last_action_date' => now()->subDays(7),
                'bill_link' => 'https://example.com/bills/SB5678',
                'sponsor' => 'David Wilson',
                'floor_sponsor' => 'Sarah Thompson',
                'ai_analysis' => 'This bill addresses critical healthcare disparities in rural areas.',
                'ai_impact_rating' => 3,
                'ai_impact_rating_explanation' => 'High impact due to targeted approach to rural healthcare access.',
                'level' => 2,
                'position' => 3,
                'date_entered' => now()->subDays(20),
                'is_tracked' => true,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'HB9012',
                'bill_year' => 2024,
                'session' => 'GEN',
                'bill_number' => 'HB9012',
                'short_title' => 'Renewable Energy Incentives',
                'general_provisions' => 'This bill introduces new incentives for renewable energy adoption.',
                'highlighted_provisions' => 'Tax credits for solar panel installation and wind energy projects.',
                'subjects' => 'Energy, Environment, Taxation',
                'code_sections' => '23-45, 67-89',
                'appropriations' => '$150 million in tax credits',
                'last_action' => 'Passed House',
                'last_action_owner' => 'House Energy Committee',
                'last_action_date' => now()->subDays(3),
                'bill_link' => 'https://example.com/bills/HB9012',
                'sponsor' => 'Lisa Chen',
                'floor_sponsor' => 'Robert Taylor',
                'ai_analysis' => 'This bill could accelerate the transition to renewable energy sources.',
                'ai_impact_rating' => 4,
                'ai_impact_rating_explanation' => 'Moderate to high impact due to financial incentives for renewable energy adoption.',
                'level' => 2,
                'position' => 2,
                'date_entered' => now()->subDays(25),
                'is_tracked' => false,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'SB3456',
                'bill_year' => 2024,
                'session' => 'SUMMER',
                'bill_number' => 'SB3456',
                'short_title' => 'Cybersecurity Enhancement Act',
                'general_provisions' => 'This bill aims to strengthen cybersecurity measures for state agencies.',
                'highlighted_provisions' => 'Mandates regular security audits and establishes a cyber response team.',
                'subjects' => 'Technology, Security',
                'code_sections' => '78-90, 12-34',
                'appropriations' => '$50 million for cybersecurity initiatives',
                'last_action' => 'In Senate Committee',
                'last_action_owner' => 'Senate Technology Committee',
                'last_action_date' => now()->subDays(1),
                'bill_link' => 'https://example.com/bills/SB3456',
                'sponsor' => 'Mark Johnson',
                'floor_sponsor' => 'Amanda Lee',
                'ai_analysis' => 'This bill addresses critical vulnerabilities in state cybersecurity.',
                'ai_impact_rating' => 5,
                'ai_impact_rating_explanation' => 'High impact due to comprehensive approach to cybersecurity threats.',
                'level' => 1,
                'position' => 4,
                'date_entered' => now()->subDays(5),
                'is_tracked' => true,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'HB7890',
                'bill_year' => 2024,
                'session' => 'GEN',
                'bill_number' => 'HB7890',
                'short_title' => 'Small Business Support Act',
                'general_provisions' => 'This bill provides support and incentives for small businesses.',
                'highlighted_provisions' => 'Tax breaks and grants for small business owners.',
                'subjects' => 'Business, Economy',
                'code_sections' => '56-78, 90-12',
                'appropriations' => '$100 million for small business grants',
                'last_action' => 'Introduced in House',
                'last_action_owner' => 'House Economic Affairs Committee',
                'last_action_date' => now()->subDays(8),
                'bill_link' => 'https://example.com/bills/HB7890',
                'sponsor' => 'Thomas Brown',
                'floor_sponsor' => 'Jennifer White',
                'ai_analysis' => 'This bill could provide significant support to small businesses.',
                'ai_impact_rating' => 6,
                'ai_impact_rating_explanation' => 'Moderate to high impact due to targeted support for small businesses.',
                'level' => 1,
                'position' => 3,
                'date_entered' => now()->subDays(12),
                'is_tracked' => false,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'SB2345',
                'bill_year' => 2024,
                'session' => 'SPEC',
                'bill_number' => 'SB2345',
                'short_title' => 'Mental Health Services Expansion',
                'general_provisions' => 'This bill expands access to mental health services.',
                'highlighted_provisions' => 'Increases funding for community mental health centers and teletherapy services.',
                'subjects' => 'Healthcare, Mental Health',
                'code_sections' => '34-56, 78-90',
                'appropriations' => '$200 million for mental health programs',
                'last_action' => 'Passed Senate Committee',
                'last_action_owner' => 'Senate Health Committee',
                'last_action_date' => now()->subDays(6),
                'bill_link' => 'https://example.com/bills/SB2345',
                'sponsor' => 'Rachel Green',
                'floor_sponsor' => 'Daniel Park',
                'ai_analysis' => 'This bill addresses the growing need for mental health services.',
                'ai_impact_rating' => 8,
                'ai_impact_rating_explanation' => 'High impact due to increased funding and focus on accessibility.',
                'level' => 2,
                'position' => 4,
                'date_entered' => now()->subDays(18),
                'is_tracked' => true,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'HB6789',
                'bill_year' => 2024,
                'session' => 'GEN',
                'bill_number' => 'HB6789',
                'short_title' => 'Affordable Housing Initiative',
                'general_provisions' => 'This bill aims to increase affordable housing options.',
                'highlighted_provisions' => 'Provides incentives for developers to build affordable housing units.',
                'subjects' => 'Housing, Urban Development',
                'code_sections' => '45-67, 89-01',
                'appropriations' => '$350 million for affordable housing projects',
                'last_action' => 'In House Committee',
                'last_action_owner' => 'House Urban Affairs Committee',
                'last_action_date' => now()->subDays(4),
                'bill_link' => 'https://example.com/bills/HB6789',
                'sponsor' => 'Olivia Martinez',
                'floor_sponsor' => 'William Lee',
                'ai_analysis' => 'This bill could significantly impact the affordable housing crisis.',
                'ai_impact_rating' => 10,
                'ai_impact_rating_explanation' => 'High impact due to substantial funding and targeted incentives.',
                'level' => 3,
                'position' => 2,
                'date_entered' => now()->subDays(22),
                'is_tracked' => true,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'SB8901',
                'bill_year' => 2024,
                'session' => 'SUMMER',
                'bill_number' => 'SB8901',
                'short_title' => 'Clean Water Act Amendment',
                'general_provisions' => 'This bill strengthens regulations on water pollution.',
                'highlighted_provisions' => 'Increases penalties for water pollution violations and funds water treatment projects.',
                'subjects' => 'Environment, Water Resources',
                'code_sections' => '12-34, 56-78',
                'appropriations' => '$250 million for water treatment and conservation',
                'last_action' => 'Introduced in Senate',
                'last_action_owner' => 'Senate Environmental Committee',
                'last_action_date' => now()->subDays(9),
                'bill_link' => 'https://example.com/bills/SB8901',
                'sponsor' => 'Christopher Wong',
                'floor_sponsor' => 'Elizabeth Taylor',
                'ai_analysis' => 'This bill could have a significant positive impact on water quality.',
                'ai_impact_rating' => 8,
                'ai_impact_rating_explanation' => 'High impact due to stricter regulations and increased funding for water projects.',
                'level' => 1,
                'position' => 5,
                'date_entered' => now()->subDays(14),
                'is_tracked' => false,
            ],
            [
                'guid' => Str::uuid()->toString(),
                'tracking_id' => 'HB4567',
                'bill_year' => 2024,
                'session' => 'GEN',
                'bill_number' => 'HB4567',
                'short_title' => 'Public Transportation Expansion Act',
                'general_provisions' => 'This bill focuses on expanding public transportation options.',
                'highlighted_provisions' => 'Funds new bus routes and light rail projects in urban areas.',
                'subjects' => 'Transportation, Urban Development',
                'code_sections' => '23-45, 67-89',
                'appropriations' => '$750 million for public transportation projects',
                'last_action' => 'Passed House',
                'last_action_owner' => 'House Transportation Committee',
                'last_action_date' => now()->subDays(11),
                'bill_link' => 'https://example.com/bills/HB4567',
                'sponsor' => 'Sophia Rodriguez',
                'floor_sponsor' => 'James Kim',
                'ai_analysis' => 'This bill could significantly improve urban mobility and reduce traffic congestion.',
                'ai_impact_rating' => 8,
                'ai_impact_rating_explanation' => 'High impact due to large-scale investment in public transportation infrastructure.',
                'level' => 2,
                'position' => 5,
                'date_entered' => now()->subDays(35),
                'is_tracked' => true,
            ],
        ];

        foreach ($bills as $bill) {
            Bill::create($bill);
        }
    }
}
